import type { StepperState, StudioPreset } from "../types";

export const DEFAULT_STEPPER_STATE: StepperState = {
  "title": "Production component",
  "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
  "label": "Component",
  "helper": "Native, buyer-ready, preview/export-honest output.",
  "id": "component-instance",
  "ariaLabel": "Component preview",
  "tabIndex": 0,
  "width": 520,
  "height": 320,
  "gap": 14,
  "padding": 24,
  "radius": 22,
  "borderWidth": 1,
  "shadow": 28,
  "background": "#0f172a",
  "foreground": "#e5eefb",
  "muted": "#94a3b8",
  "accent": "#38bdf8",
  "border": "#334155",
  "fontFamily": "Inter",
  "titleSize": 22,
  "bodySize": 14,
  "fontWeight": 700,
  "previewState": "default",
  "motion": true,
  "disabled": false,
  "role": "list",
  "itemCount": 5,
  "activeIndex": 2,
  "orientation": "horizontal",
  "connectorStyle": "solid",
  "clickable": true,
  "optionalSteps": 1,
  "errorStep": 0
};

export const STEPPER_PRESETS: StudioPreset[] = [
  {
    "id": "premium-glass-compact",
    "family": "premium",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "premium",
      "glass",
      "compact",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 24,
      "borderWidth": 1,
      "shadow": 34,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "premium-glass-spacious",
    "family": "premium",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "premium",
      "glass",
      "spacious",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 24,
      "borderWidth": 1,
      "shadow": 34,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "premium-soft-compact",
    "family": "premium",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "premium",
      "soft",
      "compact",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 28,
      "borderWidth": 1,
      "shadow": 16,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "premium-soft-spacious",
    "family": "premium",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "premium",
      "soft",
      "spacious",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 28,
      "borderWidth": 1,
      "shadow": 16,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "premium-crisp-compact",
    "family": "premium",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "premium",
      "crisp",
      "compact",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 12,
      "borderWidth": 1,
      "shadow": 8,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "premium-crisp-spacious",
    "family": "premium",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "premium",
      "crisp",
      "spacious",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 12,
      "borderWidth": 1,
      "shadow": 8,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "premium-hero-compact",
    "family": "premium",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "premium",
      "hero",
      "compact",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 32,
      "borderWidth": 1,
      "shadow": 46,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "premium-hero-spacious",
    "family": "premium",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "premium",
      "hero",
      "spacious",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 32,
      "borderWidth": 1,
      "shadow": 46,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "editorial-glass-compact",
    "family": "editorial",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "editorial",
      "glass",
      "compact",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 24,
      "borderWidth": 1,
      "shadow": 34,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "editorial-glass-spacious",
    "family": "editorial",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "editorial",
      "glass",
      "spacious",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 24,
      "borderWidth": 1,
      "shadow": 34,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "editorial-soft-compact",
    "family": "editorial",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "editorial",
      "soft",
      "compact",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 28,
      "borderWidth": 1,
      "shadow": 16,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "editorial-soft-spacious",
    "family": "editorial",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "editorial",
      "soft",
      "spacious",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 28,
      "borderWidth": 1,
      "shadow": 16,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "editorial-crisp-compact",
    "family": "editorial",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "editorial",
      "crisp",
      "compact",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 12,
      "borderWidth": 1,
      "shadow": 8,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "editorial-crisp-spacious",
    "family": "editorial",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "editorial",
      "crisp",
      "spacious",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 12,
      "borderWidth": 1,
      "shadow": 8,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "editorial-hero-compact",
    "family": "editorial",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "editorial",
      "hero",
      "compact",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 32,
      "borderWidth": 1,
      "shadow": 46,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "editorial-hero-spacious",
    "family": "editorial",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "editorial",
      "hero",
      "spacious",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 32,
      "borderWidth": 1,
      "shadow": 46,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "admin-glass-compact",
    "family": "admin",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "admin",
      "glass",
      "compact",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 24,
      "borderWidth": 1,
      "shadow": 34,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "admin-glass-spacious",
    "family": "admin",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "admin",
      "glass",
      "spacious",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 24,
      "borderWidth": 1,
      "shadow": 34,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "admin-soft-compact",
    "family": "admin",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "admin",
      "soft",
      "compact",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 28,
      "borderWidth": 1,
      "shadow": 16,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "admin-soft-spacious",
    "family": "admin",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "admin",
      "soft",
      "spacious",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 28,
      "borderWidth": 1,
      "shadow": 16,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "admin-crisp-compact",
    "family": "admin",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "admin",
      "crisp",
      "compact",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 12,
      "borderWidth": 1,
      "shadow": 8,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "admin-crisp-spacious",
    "family": "admin",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "admin",
      "crisp",
      "spacious",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 12,
      "borderWidth": 1,
      "shadow": 8,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "admin-hero-compact",
    "family": "admin",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "admin",
      "hero",
      "compact",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 32,
      "borderWidth": 1,
      "shadow": 46,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "admin-hero-spacious",
    "family": "admin",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "admin",
      "hero",
      "spacious",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 32,
      "borderWidth": 1,
      "shadow": 46,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "commerce-glass-compact",
    "family": "commerce",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "commerce",
      "glass",
      "compact",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 24,
      "borderWidth": 1,
      "shadow": 34,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "commerce-glass-spacious",
    "family": "commerce",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "commerce",
      "glass",
      "spacious",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 24,
      "borderWidth": 1,
      "shadow": 34,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "commerce-soft-compact",
    "family": "commerce",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "commerce",
      "soft",
      "compact",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 28,
      "borderWidth": 1,
      "shadow": 16,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "commerce-soft-spacious",
    "family": "commerce",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "commerce",
      "soft",
      "spacious",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 28,
      "borderWidth": 1,
      "shadow": 16,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "commerce-crisp-compact",
    "family": "commerce",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "commerce",
      "crisp",
      "compact",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 12,
      "borderWidth": 1,
      "shadow": 8,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "commerce-crisp-spacious",
    "family": "commerce",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "commerce",
      "crisp",
      "spacious",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 12,
      "borderWidth": 1,
      "shadow": 8,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "commerce-hero-compact",
    "family": "commerce",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "commerce",
      "hero",
      "compact",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 32,
      "borderWidth": 1,
      "shadow": 46,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "commerce-hero-spacious",
    "family": "commerce",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "commerce",
      "hero",
      "spacious",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 32,
      "borderWidth": 1,
      "shadow": 46,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "support-glass-compact",
    "family": "support",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "support",
      "glass",
      "compact",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 24,
      "borderWidth": 1,
      "shadow": 34,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "support-glass-spacious",
    "family": "support",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "support",
      "glass",
      "spacious",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 24,
      "borderWidth": 1,
      "shadow": 34,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "support-soft-compact",
    "family": "support",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "support",
      "soft",
      "compact",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 28,
      "borderWidth": 1,
      "shadow": 16,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "support-soft-spacious",
    "family": "support",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "support",
      "soft",
      "spacious",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 28,
      "borderWidth": 1,
      "shadow": 16,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "support-crisp-compact",
    "family": "support",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "support",
      "crisp",
      "compact",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 12,
      "borderWidth": 1,
      "shadow": 8,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "support-crisp-spacious",
    "family": "support",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "support",
      "crisp",
      "spacious",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 12,
      "borderWidth": 1,
      "shadow": 8,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "support-hero-compact",
    "family": "support",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "support",
      "hero",
      "compact",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 32,
      "borderWidth": 1,
      "shadow": 46,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "support-hero-spacious",
    "family": "support",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "support",
      "hero",
      "spacious",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 32,
      "borderWidth": 1,
      "shadow": 46,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "system-glass-compact",
    "family": "system",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "system",
      "glass",
      "compact",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 24,
      "borderWidth": 1,
      "shadow": 34,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "system-glass-spacious",
    "family": "system",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "system",
      "glass",
      "spacious",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 24,
      "borderWidth": 1,
      "shadow": 34,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "system-soft-compact",
    "family": "system",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "system",
      "soft",
      "compact",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 28,
      "borderWidth": 1,
      "shadow": 16,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "system-soft-spacious",
    "family": "system",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "system",
      "soft",
      "spacious",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 28,
      "borderWidth": 1,
      "shadow": 16,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "system-crisp-compact",
    "family": "system",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "system",
      "crisp",
      "compact",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 12,
      "borderWidth": 1,
      "shadow": 8,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "system-crisp-spacious",
    "family": "system",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "system",
      "crisp",
      "spacious",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 12,
      "borderWidth": 1,
      "shadow": 8,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "system-hero-compact",
    "family": "system",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "system",
      "hero",
      "compact",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 420,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "radius": 32,
      "borderWidth": 1,
      "shadow": 46,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  },
  {
    "id": "system-hero-spacious",
    "family": "system",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "system",
      "hero",
      "spacious",
      "stepper",
      "export-safe"
    ],
    "state": {
      "title": "Production component",
      "description": "Button-canon standalone studio with native controls, structured presets, and React-only export parity.",
      "label": "Component",
      "helper": "Native, buyer-ready, preview/export-honest output.",
      "id": "component-instance",
      "ariaLabel": "Component preview",
      "tabIndex": 0,
      "width": 640,
      "height": 420,
      "gap": 20,
      "padding": 30,
      "radius": 32,
      "borderWidth": 1,
      "shadow": 46,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "fontFamily": "Inter",
      "titleSize": 22,
      "bodySize": 14,
      "fontWeight": 700,
      "previewState": "default",
      "motion": true,
      "disabled": false,
      "role": "list",
      "itemCount": 5,
      "activeIndex": 2,
      "orientation": "horizontal",
      "connectorStyle": "solid",
      "clickable": true,
      "optionalSteps": 1,
      "errorStep": 0
    }
  }
];
